### ISSUE TITLE
MongoDB Team Account on mLab

### ISSUE THREAD

**Issue by anthonydevelops** [chtzou/Slug-Academic-Organizer#6]
For MongoDB, it might be troublesome to use each of our own servers and update drivers throughout if they aren't all already updated to the latest. Also, keeping our database in sync itself would be tough. There is a service called mLab [https://mlab.com/](url) which is hosted virtual mongoDB servers, and maybe we could create a team account so all of us could log in to check how the data is going through? It's free and always upgradeable, no credit card required either.

**Comment by hannah-ekman** [comment]
Yeah sure. That sounds useful.
