### ISSUE TITLE
Create Table-like UI for Class Input

### ISSUE THREAD

**Issue by anthonydevelops** [chtzou/Slug-Academic-Organizer#9]
We'll need to create a table-like UI component for our user to input their class schedule. There are many ways to create this, but for this one, we'll want them to input their courseID (CMPSXXX), course title, lecture time & days, and optionally an input for labs. Each row will represent a class, each column will represent a section (such as courseID column, title column, etc). I say rows and columns because it will essentially be a table, but the design is up for interpretation based off what we think might look nice and unique. Tables are good! Thinking outside the box is good too! If you'd like to do this task, feel free to assign yourself & let us know what you'd think of making it look like.

**Comment by hannah-ekman** [comment]
Would it be possible-for a future enhancement-to have it search the pisa website for the class to automatically fill in lecture times? Idk something to think about.

**Comment by anthonydevelops** [comment]
I definitely think it is possible, right now I'm using a different url that points to https://courses.soe.ucsc.edu/ to gather classID, class title, departments, and eventually each class as seen in the schedule. One thing I'm uncertain about is the specific class data, such as times/days/enrollment info/etc, since this url I'm currently using doesn't give me that. I would have to use the url https://pisa.ucsc.edu/class_search/ for that, but the issue I was having was getting the data from the classes, since it seems to be a dynamic page and I'm not able to scrape data off as easily with Cheerio.

**Comment by anthonydevelops** [comment]
Maybe we could look into something like https://github.com/GoogleChrome/puppeteer, since I've read that it is able to scrape dynamic data from pages I think. I've never used it, but yeah to answer your question, we can definitely figure out a way to scrape the data from the pisa website, but it'll take maybe some more time to research how.

**Comment by hannah-ekman** [comment]
Yeah it's fine if we don't get to it LOL but yeah for the future, I think it'd be really cool if we did implement it.
